const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  DIRECTIVO: 'DIRECTIVO',
  INSPECTORIA: 'INSPECTORIA',
  DOCENTE: 'DOCENTE',
  ENCARGADO: 'ENCARGADO'
});

const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.ADMIN]: ['*'],
  [ROLES.DIRECTIVO]: [
    'DASHBOARD:READ',
    'REPORTS:READ',
    'REPORTS:EXPORT',
    'RESOURCES:READ',
    'LOANS:READ',
    'REQUESTS:READ',
    'REQUESTS:REVIEW',
    'PRINTS:READ',
    'PRINTS:CREATE'
  ],
  [ROLES.INSPECTORIA]: [
    'DASHBOARD:READ',
    'RESOURCES:READ',
    'RESOURCES:WRITE',
    'LOANS:READ',
    'LOANS:WRITE',
    'RESERVATIONS:READ',
    'RESERVATIONS:WRITE',
    'REQUESTS:READ',
    'REQUESTS:WRITE',
    'PRINTS:READ',
    'PRINTS:WRITE',
    'AUDIT:READ'
  ],
  [ROLES.DOCENTE]: [
    'DASHBOARD:READ',
    'RESOURCES:READ',
    'LOANS:READ_OWN',
    'RESERVATIONS:READ_OWN',
    'RESERVATIONS:CREATE',
    'REQUESTS:READ_OWN',
    'REQUESTS:CREATE',
    'PRINTS:READ_OWN',
    'PRINTS:CREATE'
  ],
  [ROLES.ENCARGADO]: [
    'DASHBOARD:READ',
    'RESOURCES:READ',
    'RESOURCES:WRITE_AREA',
    'LOANS:READ',
    'RESERVATIONS:READ',
    'PRINTS:READ',
    'PRINTS:CREATE',
    'PRINTS:REVIEW'
  ]
});

const ALL_ROLES = Object.freeze(Object.values(ROLES));

const getRolePermissions = (roleName) => ROLE_PERMISSIONS[roleName] || [];

module.exports = {
  ROLES,
  ALL_ROLES,
  ROLE_PERMISSIONS,
  getRolePermissions
};





